title        = "tttardigrado"
languageCode = "pt-pt"
paginate     = 10

[params]
  desc = "às vezes escrevo umas cenas"
  lang = [".pt", ".en", ".hs"]
  socials = [ 
    { url = "https://www.instagram.com/ttttardigrado/", name = "insta" }
  , { url = "https://github.com/tttardigrado", name = "github" }
  ]
