baseURL: "https://tttardigrado.github.io/"
languageCode: "en-us"
title: "Tardigrado"

theme: "nordTerm"

frontmatter:
  date:
    - publishDate
    - :filename
    - date
    - :fileModTime

params:
  social:
    - icon: "github"
      url:  "https://github.com/tttardigrado"
    - icon: "twitter"
      url:  "https://twitter.com/_tardigrado_"
    - icon: "instagram"
      url:  "https://www.instagram.com/_tardigrado_/"
  
  colors:
    bgDark: "#2e3440"
    bgLight: "#3b4252"
    text: "#d8dee9"    
    error: "#bf616a"
    alert: "#ebcb8b"
    success: "#a3be8c"
    primary: "#a3be8c"
    secondary: "#b48ead"