baseURL: 'http://tttardigrado.github.com/'
languageCode: 'en-us'
title: 'tttardigrado'

params:
  pagination: 4

  nav:
    - name: tttardigrade
      url: "/"
    - name: blog
      url: "/blog/"
    - name: cv
      url: "/cv"
 
  footer:
    - name: git
      url: "https://github.com/tttardigrado"
      icon: "bi-git"
    - name: rss
      url: "index.xml"
      icon: "bi-rss-fill"
    - name: e-mail
      url: "mailto:tttardigrado@proton.me"
      icon: "bi-envelope-fill"
